# Generated by Django 4.1.7 on 2023-03-28 12:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floors_cnt', models.IntegerField()),
                ('elevator_cnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('elevator_id', models.IntegerField(primary_key=True, serialize=False)),
                ('door_status', models.BooleanField(default=False)),
                ('is_in_order', models.BooleanField(default=True)),
                ('destinations', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('Elevator_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator_api.elevator_system')),
            ],
        ),
    ]
