# Generated by Django 4.1.7 on 2023-04-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='current_floor',
            field=models.IntegerField(default=0),
        ),
    ]
